name: Cloudinary â†’ JSON Sync

on:
  schedule:
    - cron: "0 */2 * * *"   # every 1 hour
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install cloudinary

      - name: Run Cloudinary Sync
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: node scripts/cloudinary-sync.mjs

      - name: Commit & Push JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/json/cloudinary.json
          git diff --cached --quiet || git commit -m "auto: update cloudinary.json"
          git push
